version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    # env_file:
    #   - ./.env
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123"
      POSTGRES_DB: "postgres"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   restart: unless-stopped

volumes:
  progresDB: